version: '3'
services:

    gokopa:
        image: leafarlins/gokopa
        #build: .
        #restart: always
        #volumes:
        #- "./volume/data:/var/cells/data"
        #  - "data:/var/cells/data"
        #  - "cellsdir:/var/cells"
        ports: ["8081:5000"]
        environment:
          FLASK_APP: app.py
          FLASK_ENV: development
          MONGO_URI: ${MONGO_URI}
          SECRET_KEY: ${SECRET_KEY}

    #mongodb:
        #image: 
