version: '3'
services:

    gokopa:
        #image: gokopa:0.1.0
        build: .
        #restart: always
        #volumes:
        #- "./volume/data:/var/cells/data"
        #  - "data:/var/cells/data"
        #  - "cellsdir:/var/cells"
        ports: ["8080:5000"]
        environment:
          FLASK_APP: app/app.py
          MONGO_URI: ${MONGO_URI}
          SECRET_KEY: ${SECRET_KEY}

    #mongodb:
        #image: 
