version: '3'
services:

    gokopa:
        #image: gokopa:0.1.0
        build: .
        #restart: always
        #volumes:
        #- "./volume/data:/var/cells/data"
        #  - "data:/var/cells/data"
        #  - "cellsdir:/var/cells"
        ports: ["8081:5000"]
        command:
            - run
            - --host=0.0.0.0
        environment:
          FLASK_APP: app.py
          FLASK_ENV: development
          MONGO_URI: ${MONGO_URI}
          SECRET_KEY: ${SECRET_KEY}

    #mongodb:
        #image: 
